server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    name: user
    password: password123

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
    #下面两行作用：只能将其作为eureka server，不能将其作为eureka client
    register-with-eureka: false
    fetch-registry: false
