server:
  port: 7901
user.userPath: http://localhost:7900/simple/

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  application:
    name: microservice-consumer-movie
